<?php
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function iq_group_bw2_form_alter(&$form, FormStateInterface $form_state, $form_id) {

  // Disable cancel methods for non-admin users.
  if ($form_id == 'user_register_form') {
    $form['group_user_profile']['field_iq_user_base_salutation'] = [
      '#type' => 'select',
      '#title' => t('Anrede'),
      '#default_value' => false,
      '#required' => true,
      '#options' => [
          'Herr' => 'Herr',
          'Frau' => 'Frau',
          'Mr.' => 'Mr.',
          'Miss' => 'Miss',
          'Misses' => 'Misses'
      ],
      '#weight' => 0,
    ];
    $form['group_user_profile']['field_iq_user_base_adress_pobox'] = [
      '#type' => 'textfield',
      '#title' => t('Postfach'),
      '#default_value' => false,
      '#required' => false,
      '#weight' => 10,
    ];
  }
}